SET SERVEROUTPUT ON;

CREATE TABLE Sitio_Adultos(ID INTEGER PRIMARY KEY,Nombre VARCHAR2(30),Edad INTEGER);
CREATE SEQUENCE SEC_AUTOINCREMENT
START WITH 5
INCREMENT BY 1
NOMAXVALUE;

CREATE OR REPLACE PROCEDURE ALMACENAR(ID_BEFORE OUT INTEGER,Nombre_BEFORE IN VARCHAR2,Edad_BEFORE IN INTEGER)
AS 
BEGIN
SELECT SEC_AUTOINCREMENT.NEXTVAL INTO ID_BEFORE FROM DUAL;
INSERT INTO Sitio_Adultos VALUES(ID_BEFORE,Nombre_BEFORE,Edad_BEFORE);
END;
/

